/**
 * Canonical product import schema (Import-1A).
 * Single source of truth for CSV headers, XLSX sheets, Field Reference, and future parser/validation.
 * Read-only templates only — no DB writes.
 */

const TEMPLATE_VERSION = "product-import-schema-v1.0";

const PRODUCT_TYPE_VALUES = ["simple", "variable", "variation"];
const PRODUCT_STATUS_VALUES = ["draft", "published", "inactive"];
/** Import-2 preview: strict status check per phase requirements */
const PREVIEW_STATUS_VALUES = ["draft", "published", "inactive"];

const IMPORT_HEADER_ALIASES = {
  stock_quantity: "stock",
  featured_image_url: "featured_image",
  gallery_image_urls: "gallery_images",
  product_title: "product_name",
  name: "product_name",
  productname: "product_name",
  type: "product_type",
  producttype: "product_type",
  parentsku: "parent_sku",
  templateversion: "template_version",
  quantity: "stock",
  saleprice: "sale_price",
  unittype: "unit_type",
  shortdescription: "short_description",
  featuredimage: "featured_image",
  galleryimages: "gallery_images",
};

/**
 * @typedef {Object} ProductImportColumn
 * @property {string} key
 * @property {string} label
 * @property {"yes"|"optional"|"conditional"} required
 * @property {string[]} [requiredFor]
 * @property {string} [conditionalFor]
 * @property {string} type
 * @property {string|null} mapsTo
 * @property {string} example
 * @property {string} description
 * @property {string} acceptedValues
 * @property {string} appliesTo
 */

/** @type {ProductImportColumn[]} */
const PRODUCT_IMPORT_COLUMNS = [
  {
    key: "template_version",
    label: "Template Version",
    required: "yes",
    requiredFor: ["simple", "variable", "variation"],
    type: "string",
    mapsTo: null,
    example: TEMPLATE_VERSION,
    description: "Schema version for import compatibility checks.",
    acceptedValues: TEMPLATE_VERSION,
    appliesTo: "all",
  },
  {
    key: "product_type",
    label: "Product Type",
    required: "yes",
    requiredFor: ["simple", "variable", "variation"],
    type: "enum",
    mapsTo: null,
    example: "simple",
    description: "Row role: simple product, variable parent, or variation child.",
    acceptedValues: PRODUCT_TYPE_VALUES.join(", "),
    appliesTo: "all",
  },
  {
    key: "parent_sku",
    label: "Parent SKU",
    required: "conditional",
    conditionalFor: "variation",
    requiredFor: ["variation"],
    type: "string",
    mapsTo: null,
    example: "HD-100",
    description:
      "SKU of the variable parent row. Required for variation rows; must appear earlier in the file.",
    acceptedValues: "Existing variable parent SKU in file or catalog",
    appliesTo: "variation",
  },
  {
    key: "product_name",
    label: "Product Name",
    required: "yes",
    requiredFor: ["simple", "variable", "variation"],
    type: "string",
    mapsTo: "name",
    example: "Classic Cotton T-Shirt",
    description: "Display name shown in admin and storefront.",
    acceptedValues: "Any text",
    appliesTo: "all",
  },
  {
    key: "slug",
    label: "Slug",
    required: "optional",
    type: "string",
    mapsTo: "slug",
    example: "classic-cotton-tee",
    description: "URL slug; auto-generated from name when omitted on create.",
    acceptedValues: "URL-safe string",
    appliesTo: "simple, variable",
  },
  {
    key: "sku",
    label: "SKU",
    required: "yes",
    requiredFor: ["simple", "variable", "variation"],
    type: "string",
    mapsTo: "sku",
    example: "TEE-001",
    description: "Globally unique stock keeping unit (parent or variation).",
    acceptedValues: "Unique per row; text format in Excel",
    appliesTo: "all",
  },
  {
    key: "category",
    label: "Category",
    required: "conditional",
    conditionalFor: "simple",
    requiredFor: ["simple"],
    type: "string",
    mapsTo: "category",
    example: "Apparel > Tees",
    description:
      "Category name or breadcrumb path; resolved to Category ObjectId on import.",
    acceptedValues: "Name or path matching an existing category",
    appliesTo: "simple, variable (recommended on parent)",
  },
  {
    key: "brand",
    label: "Brand",
    required: "optional",
    type: "string",
    mapsTo: "brand",
    example: "Acme Brand",
    description: "Brand name; resolved to Brand ObjectId on import.",
    acceptedValues: "Name matching an existing brand",
    appliesTo: "simple, variable",
  },
  {
    key: "unit_type",
    label: "Unit Type",
    required: "optional",
    type: "string",
    mapsTo: "unitType",
    example: "piece",
    description: "Unit of measure name; resolved to UnitType ObjectId on import.",
    acceptedValues: "Name matching an existing unit type",
    appliesTo: "simple, variable",
  },
  {
    key: "status",
    label: "Status",
    required: "optional",
    type: "enum",
    mapsTo: "status",
    example: "published",
    description:
      "Product listing status. Variation rows may set status; importer maps variation rows to variations[].status when supported.",
    acceptedValues: PRODUCT_STATUS_VALUES.join(", "),
    appliesTo: "all",
  },
  {
    key: "short_description",
    label: "Short Description",
    required: "optional",
    type: "text",
    mapsTo: "shortDescription",
    example: "Soft cotton everyday tee.",
    description: "Brief plain text or safe HTML summary.",
    acceptedValues: "Plain text or safe HTML",
    appliesTo: "simple, variable",
  },
  {
    key: "description",
    label: "Description",
    required: "optional",
    type: "text",
    mapsTo: "description",
    example: "Comfortable crew neck tee for daily wear.",
    description: "Full product description (plain text or safe HTML).",
    acceptedValues: "Plain text or safe HTML",
    appliesTo: "simple, variable",
  },
  {
    key: "price",
    label: "Price",
    required: "conditional",
    conditionalFor: "simple, variation",
    requiredFor: ["simple", "variation"],
    type: "number",
    mapsTo: "price",
    example: "29.99",
    description: "Base price. Required on simple and variation rows; optional on variable parent.",
    acceptedValues: "Decimal >= 0",
    appliesTo: "simple, variation (optional on variable parent)",
  },
  {
    key: "sale_price",
    label: "Sale Price",
    required: "optional",
    type: "number",
    mapsTo: "salePrice",
    example: "24.99",
    description: "Discounted price; must be <= price when set.",
    acceptedValues: "Decimal >= 0",
    appliesTo: "simple, variation",
  },
  {
    key: "stock",
    label: "Stock",
    required: "optional",
    type: "integer",
    mapsTo: "quantity",
    example: "100",
    description: "Inventory quantity. Maps to Product.quantity or variations[].quantity.",
    acceptedValues: "Integer >= 0",
    appliesTo: "simple, variation",
  },
  {
    key: "featured_image",
    label: "Featured Image",
    required: "optional",
    type: "url",
    mapsTo: "featuredImage",
    example: "https://cdn.example.com/tee-001.jpg",
    description:
      "Primary image URL or server path. On import, linked to a Media Library record (featuredMediaId) while keeping the URL on the product.",
    acceptedValues: "http(s) URL or server path",
    appliesTo: "simple, variable, variation",
  },
  {
    key: "gallery_images",
    label: "Gallery Images",
    required: "optional",
    type: "string",
    mapsTo: "galleryImages",
    example: "https://cdn.example.com/a.jpg|https://cdn.example.com/b.jpg",
    description: "Multiple image URLs separated by pipe (|). Each URL is linked to Media Library records on import.",
    acceptedValues: "Pipe-separated URLs",
    appliesTo: "simple, variable",
  },
  {
    key: "attribute_1_name",
    label: "Attribute 1 Name",
    required: "conditional",
    conditionalFor: "variable",
    type: "string",
    mapsTo: "attributes[].name",
    example: "Color",
    description: "First variation attribute label on variable parent; value on variation rows.",
    acceptedValues: "Catalog attribute name",
    appliesTo: "variable (name), variation (value)",
  },
  {
    key: "attribute_1_value",
    label: "Attribute 1 Value",
    required: "conditional",
    conditionalFor: "variation",
    type: "string",
    mapsTo: "variations[].attributes[].value",
    example: "Red",
    description: "Value for attribute 1 on variation rows.",
    acceptedValues: "Defined attribute value",
    appliesTo: "variation",
  },
  {
    key: "attribute_2_name",
    label: "Attribute 2 Name",
    required: "optional",
    type: "string",
    mapsTo: "attributes[].name",
    example: "Size",
    description: "Second variation attribute label on variable parent.",
    acceptedValues: "Catalog attribute name",
    appliesTo: "variable (name), variation (value)",
  },
  {
    key: "attribute_2_value",
    label: "Attribute 2 Value",
    required: "optional",
    type: "string",
    mapsTo: "variations[].attributes[].value",
    example: "M",
    description: "Value for attribute 2 on variation rows.",
    acceptedValues: "Defined attribute value",
    appliesTo: "variation",
  },
  {
    key: "variation_options",
    label: "Variation Options",
    required: "optional",
    type: "string",
    mapsTo: null,
    example: "Color;Size",
    description: "Variation axes on variable parent; semicolon-separated attribute names.",
    acceptedValues: "Semicolon-separated names",
    appliesTo: "variable",
  },
  {
    key: "seo_title",
    label: "SEO Title",
    required: "optional",
    type: "string",
    mapsTo: null,
    example: "Classic Cotton Tee | Acme Store",
    description: "Future SEO field; ignored by importer until Product schema supports it.",
    acceptedValues: "Any text",
    appliesTo: "simple, variable",
  },
  {
    key: "seo_description",
    label: "SEO Description",
    required: "optional",
    type: "string",
    mapsTo: null,
    example: "Shop our classic cotton tee.",
    description: "Future SEO field; ignored by importer until Product schema supports it.",
    acceptedValues: "Any text",
    appliesTo: "simple, variable",
  },
  {
    key: "tags",
    label: "Tags",
    required: "optional",
    type: "string",
    mapsTo: null,
    example: "tee,cotton,basics",
    description: "Comma-separated tags for future catalog features.",
    acceptedValues: "Comma-separated values",
    appliesTo: "simple, variable",
  },
  {
    key: "weight",
    label: "Weight",
    required: "optional",
    type: "number",
    mapsTo: null,
    example: "0.25",
    description: "Product weight for future shipping calculations.",
    acceptedValues: "Decimal >= 0",
    appliesTo: "all",
  },
  {
    key: "length",
    label: "Length",
    required: "optional",
    type: "number",
    mapsTo: null,
    example: "30",
    description: "Package length for future shipping.",
    acceptedValues: "Decimal >= 0",
    appliesTo: "all",
  },
  {
    key: "width",
    label: "Width",
    required: "optional",
    type: "number",
    mapsTo: null,
    example: "25",
    description: "Package width for future shipping.",
    acceptedValues: "Decimal >= 0",
    appliesTo: "all",
  },
  {
    key: "height",
    label: "Height",
    required: "optional",
    type: "number",
    mapsTo: null,
    example: "2",
    description: "Package height for future shipping.",
    acceptedValues: "Decimal >= 0",
    appliesTo: "all",
  },
];

const IMPORT_HEADERS = PRODUCT_IMPORT_COLUMNS.map((column) => column.key);

const CANONICAL_HEADER_KEYS = new Set(IMPORT_HEADERS);

const EXAMPLE_ROWS = [
  {
    template_version: TEMPLATE_VERSION,
    product_type: "simple",
    parent_sku: "",
    product_name: "Classic Cotton Tee",
    slug: "classic-cotton-tee",
    sku: "TEE-001",
    category: "Apparel > Tees",
    brand: "Acme Brand",
    unit_type: "piece",
    status: "published",
    short_description: "Soft cotton everyday tee.",
    description: "Comfortable crew neck tee for daily wear.",
    price: "29.99",
    sale_price: "24.99",
    stock: "100",
    featured_image: "https://cdn.example.com/tee-001.jpg",
    gallery_images:
      "https://cdn.example.com/tee-001-a.jpg|https://cdn.example.com/tee-001-b.jpg",
    attribute_1_name: "",
    attribute_1_value: "",
    attribute_2_name: "",
    attribute_2_value: "",
    variation_options: "",
    seo_title: "Classic Cotton Tee | Acme Store",
    seo_description: "Shop our classic cotton tee.",
    tags: "tee,cotton,basics",
    weight: "0.25",
    length: "30",
    width: "25",
    height: "2",
  },
  {
    template_version: TEMPLATE_VERSION,
    product_type: "variable",
    parent_sku: "",
    product_name: "Hooded Sweatshirt",
    slug: "hooded-sweatshirt",
    sku: "HD-100",
    category: "Apparel > Hoodies",
    brand: "Acme Brand",
    unit_type: "piece",
    status: "published",
    short_description: "Warm layered hoodie.",
    description: "Premium fleece hoodie with kangaroo pocket.",
    price: "59.99",
    sale_price: "",
    stock: "0",
    featured_image: "https://cdn.example.com/hd-100.jpg",
    gallery_images: "https://cdn.example.com/hd-100-alt.jpg",
    attribute_1_name: "Color",
    attribute_1_value: "",
    attribute_2_name: "Size",
    attribute_2_value: "",
    variation_options: "Color;Size",
    seo_title: "Hooded Sweatshirt",
    seo_description: "Variable product parent row.",
    tags: "hoodie,apparel",
    weight: "",
    length: "",
    width: "",
    height: "",
  },
  {
    template_version: TEMPLATE_VERSION,
    product_type: "variation",
    parent_sku: "HD-100",
    product_name: "Hooded Sweatshirt - Red / M",
    slug: "",
    sku: "HD-100-RED-M",
    category: "",
    brand: "",
    unit_type: "",
    status: "published",
    short_description: "",
    description: "",
    price: "59.99",
    sale_price: "49.99",
    stock: "25",
    featured_image: "",
    gallery_images: "",
    attribute_1_name: "Color",
    attribute_1_value: "Red",
    attribute_2_name: "Size",
    attribute_2_value: "M",
    variation_options: "",
    seo_title: "",
    seo_description: "",
    tags: "",
    weight: "0.6",
    length: "",
    width: "",
    height: "",
  },
  {
    template_version: TEMPLATE_VERSION,
    product_type: "variation",
    parent_sku: "HD-100",
    product_name: "Hooded Sweatshirt - Blue / L",
    slug: "",
    sku: "HD-100-BLU-L",
    category: "",
    brand: "",
    unit_type: "",
    status: "published",
    short_description: "",
    description: "",
    price: "59.99",
    sale_price: "",
    stock: "10",
    featured_image: "https://cdn.example.com/hd-100-blu-l.jpg",
    gallery_images: "",
    attribute_1_name: "Color",
    attribute_1_value: "Blue",
    attribute_2_name: "Size",
    attribute_2_value: "L",
    variation_options: "",
    seo_title: "",
    seo_description: "",
    tags: "",
    weight: "0.6",
    length: "",
    width: "",
    height: "",
  },
];

const IMPORT_FIELD_MAPPING = [
  { importKey: "product_name", backendField: "name", notes: "Required on all row types." },
  { importKey: "sku", backendField: "sku", notes: "Parent SKU on simple/variable; variation SKU on child rows." },
  { importKey: "slug", backendField: "slug", notes: "Optional; auto-slugify from name when omitted." },
  { importKey: "stock", backendField: "quantity", notes: "Simple → Product.quantity; variation → variations[].quantity." },
  { importKey: "featured_image", backendField: "featuredImage", notes: "Also sets featuredMediaId via Media Library on import." },
  { importKey: "gallery_images", backendField: "galleryImages", notes: "Split on |; also sets galleryMediaIds via Media Library on import." },
  { importKey: "category", backendField: "category", notes: "Name/path resolver → Category ObjectId." },
  { importKey: "brand", backendField: "brand", notes: "Name resolver → Brand ObjectId." },
  { importKey: "unit_type", backendField: "unitType", notes: "Name resolver → UnitType ObjectId." },
  { importKey: "seo_title", backendField: null, notes: "Ignored until schema supports SEO." },
  { importKey: "seo_description", backendField: null, notes: "Ignored until schema supports SEO." },
  {
    importKey: "product_type",
    backendField: null,
    notes: "simple → single product; variable + variation rows → Product with variations[].",
  },
];

const normalizeImportHeaderKey = (rawHeader) => {
  const normalized = String(rawHeader ?? "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "_");
  if (!normalized) return "";
  return IMPORT_HEADER_ALIASES[normalized] || normalized;
};

const normalizeImportRow = (rawRow = {}) => {
  const normalized = {};
  Object.entries(rawRow).forEach(([key, value]) => {
    const canonicalKey = normalizeImportHeaderKey(key);
    if (!canonicalKey) return;
    const text = value === null || value === undefined ? "" : String(value).trim();
    normalized[canonicalKey] = text;
  });
  return normalized;
};

const rowToOrderedValues = (rowObject) =>
  IMPORT_HEADERS.map((key) => rowObject[key] ?? "");

const buildFieldReferenceRows = () => {
  const header = [
    "field_key",
    "label",
    "required",
    "applies_to",
    "data_type",
    "accepted_values",
    "maps_to",
    "description",
    "example",
  ];

  const rows = PRODUCT_IMPORT_COLUMNS.map((column) => [
    column.key,
    column.label,
    column.required,
    column.appliesTo,
    column.type,
    column.acceptedValues,
    column.mapsTo ?? "",
    column.description,
    column.example,
  ]);

  return [header, ...rows];
};

const buildInstructionsRows = () => [
  ["Product Import Template — Canonical Schema v1.0"],
  ["Schema version", TEMPLATE_VERSION],
  [""],
  ["Before you import"],
  ["1. Enter data on the Products sheet only (row 1 = headers, no comment rows in CSV)."],
  ["2. product_type: simple | variable | variation"],
  ["3. Place the variable parent row BEFORE its variation child rows (same parent_sku)."],
  ["4. variation rows: parent_sku must match a variable row SKU above in the file."],
  ["5. gallery_images: separate multiple URLs with pipe | (example: url1|url2)"],
  ["6. variation_options (variable parent): semicolon-separated attribute names (example: Color;Size)"],
  ["7. status (product rows): draft | published | inactive"],
  ["8. Variation rows: use featured_image for per-variation image URL (stored on variations[].image)."],
  ["9. Featured and gallery image URLs are linked to Media Library records during import."],
  ["10. category, brand, unit_type: matched by name/path during import (must exist in catalog)."],
  ["11. seo_title and seo_description: included for future use; not saved until schema supports SEO."],
  ["12. Product import is live — use Product Imports in the admin or the import API."],
  ["13. Workflow: upload file → preview with column mapping → review validation → commit."],
  ["14. CSV and XLSX templates are generated from this schema; download either format before filling data."],
  ["15. Each import run is recorded in import history; failed rows can be downloaded as an error CSV."],
  [""],
  ["Required summary by product_type"],
  ["simple", "product_type, product_name, sku, price, category (validation-required)"],
  ["variable", "product_type, product_name, sku"],
  ["variation", "product_type, parent_sku, product_name, sku, price, attribute values"],
  [""],
  ["Source of truth: backend/src/config/productImportSchema.js"],
];

module.exports = {
  TEMPLATE_VERSION,
  PRODUCT_TYPE_VALUES,
  PRODUCT_STATUS_VALUES,
  PREVIEW_STATUS_VALUES,
  PRODUCT_IMPORT_COLUMNS,
  IMPORT_HEADERS,
  IMPORT_HEADER_ALIASES,
  CANONICAL_HEADER_KEYS,
  EXAMPLE_ROWS,
  IMPORT_FIELD_MAPPING,
  normalizeImportHeaderKey,
  normalizeImportRow,
  rowToOrderedValues,
  buildFieldReferenceRows,
  buildInstructionsRows,
};
